print("Ingresa los numeros")
q=int(input())
w=int(input())
e=int(input())
r=int(input())
t=int(input())
y=int(input())
u=int(input())
i=int(input())
o=int(input())
p=int(input())
print(q+w+e+r+t+y+u+i+o+p)
